// <auto-generated />
using System;
using EShopLite.Infrastructure.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EShopLite.Infrastructure.Migrations
{
    [DbContext(typeof(EshopLiteDbContext))]
    [Migration("20250319083918_initV4")]
    partial class initV4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EShopLite.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elektronik"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Giyim"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mobilya"
                        });
                });

            modelBuilder.Entity("EShopLite.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("https://picsum.photos/200");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Apple Iphone 12 64 GB",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Iphone 12",
                            Price = 10000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Samsung",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Samsung S21",
                            Price = 9000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Tshirt",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Tshirt",
                            Price = 100m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Pantolon",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Pantolon",
                            Price = 200m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Masa",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Masa",
                            Price = 500m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Sandalye",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Sandalye",
                            Price = 200m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Laptop",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Laptop",
                            Price = 15000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Tablet",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Tablet",
                            Price = 5000m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Kulaklık",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Kulaklık",
                            Price = 500m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Televizyon",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Televizyon",
                            Price = 8000m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Kazak",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Kazak",
                            Price = 150m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Mont",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Mont",
                            Price = 300m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Ayakkabı",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Ayakkabı",
                            Price = 250m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Şapka",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Şapka",
                            Price = 50m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Ceket",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Ceket",
                            Price = 400m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Elbise",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Elbise",
                            Price = 350m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "Dolap",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Dolap",
                            Price = 2000m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "Koltuk",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Koltuk",
                            Price = 3000m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Description = "Sehpa",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Sehpa",
                            Price = 400m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Description = "Kitaplık",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Kitaplık",
                            Price = 600m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Description = "Yatak",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Yatak",
                            Price = 2500m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "Komodin",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Komodin",
                            Price = 300m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 3,
                            Description = "Lamba",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Lamba",
                            Price = 150m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Description = "Raf",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Raf",
                            Price = 200m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 3,
                            Description = "Baza",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Baza",
                            Price = 1000m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            Description = "Perde",
                            ImageUrl = "https://picsum.photos/200",
                            Name = "Perde",
                            Price = 200m,
                            Stock = 70
                        });
                });

            modelBuilder.Entity("EShopLite.Domain.Product", b =>
                {
                    b.HasOne("EShopLite.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EShopLite.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
